name: Build YAMCL

permissions:
  contents: write

on:
  push:
    tags:
      - 'v*'

jobs:
  build-linux:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v6

      - name: Setup .NET 9
        uses: actions/setup-dotnet@v5
        with:
          dotnet-version: "9.0.x"

      - name: Build Linux
        working-directory: YetAnotherMinecraftLauncher
        run: dotnet publish -c Release -r linux-x64 --self-contained true -o ../build/linux

      - name: Zip Linux build
        run: zip -r build/YAMCL-linux.zip build/linux

      - name: Upload Linux artifact
        uses: actions/upload-artifact@v6
        with:
          name: YAMCL-linux
          path: build/YAMCL-linux.zip

  build-win:
    runs-on: windows-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v6

      - name: Setup .NET 9
        uses: actions/setup-dotnet@v5
        with:
          dotnet-version: "9.0.x"

      - name: Build Windows
        working-directory: YetAnotherMinecraftLauncher
        run: dotnet publish -c Release -r win-x64 --self-contained true -o ../build/win

      - name: Zip Windows build
        run: powershell Compress-Archive -Path build\win\* -DestinationPath build\YAMCL-win.zip

      - name: Upload Windows artifact
        uses: actions/upload-artifact@v6
        with:
          name: YAMCL-win
          path: build/YAMCL-win.zip

  release:
    needs: [build-linux, build-win]
    runs-on: ubuntu-latest
    steps:
      - name: Create GitHub Release
        id: create-release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref_name }}
          release_name: YAMCL ${{ github.ref_name }}
          draft: false
          prerelease: false

      - name: Download Linux artifact
        uses: actions/download-artifact@v6
        with:
          name: YAMCL-linux
          path: build/

      - name: Download Windows artifact
        uses: actions/download-artifact@v6
        with:
          name: YAMCL-win
          path: build/

      - name: Upload Linux build to release
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create-release.outputs.upload_url }}
          asset_path: build/YAMCL-linux.zip
          asset_name: YAMCL-linux.zip
          asset_content_type: application/zip

      - name: Upload Windows build to release
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create-release.outputs.upload_url }}
          asset_path: build/YAMCL-win.zip
          asset_name: YAMCL-win.zip
          asset_content_type: application/zip
