name: Build YAMCL

on:
  push:
    branches: ['main']
    tags:
      - "v*"
    
jobs:
  build-linux:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6

      - name: "Setup .NET 9"
        uses: actions/setup-dotnet@v5
        with:
          dotnet-version: "9.0.x"

      - name: "Prepare for release"
        run: dotnet publish --no-logo -c Release -r linux-x64 --self-contained true -o build/linux

      - name: "Upload as an artifact"
        uses: actions/upload-artifact@v6
        with:
          name: YAMCL-linux
          path: build/linux

  build-win:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v6

      - name: "Setup .NET 9"
        uses: actions/setup-dotnet@v5
        with:
          dotnet-version: "9.0.x"

      - name: "Prepare for release"
        run: dotnet publish --no-logo -c Release -r win-x64 --self-contained true -o build/win

      - name: "Upload as an artifact"
        uses: actions/upload-artifact@v6
        with:
          name: YAMCL-win
          path: build/win

  release:
    runs-on: ubuntu-latest
    needs: [build-win, build-linux]
    steps:
      - name: "Create the release"
        id: create-release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: YAMCL ${{ github.ref }}
          draft: false
          prerelease: false

      - name: "ownload Linux artifact"
        uses: actions/download-artifact@v3
        with:
          name: YAMCL-linux
          path: build/

      - name: "Download Windows artifact"
        uses: actions/download-artifact@v3
        with:
          name: YAMCL-win
          path: build/

      - name: "Upload release asset (Linux)"
        id: upload-release-asset-linux
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create-release.outputs.upload_url }}
          asset_path: build/linux
          asset_name: YAMCL-linux.zip
          asset_content_type: application/zip

      - name: "Upload release asset (Windows)"
        id: upload-release-asset-win
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create-release.outputs.upload_url }}
          asset_path: build/win
          asset_name: YAMCL-win.zip
          asset_content_type: application/zip