name: Build YAMCL

permissions:
  contents: write

on:
  push:
    tags:
      - "v*"

jobs:
  build-linux:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v5
        with:
          dotnet-version: "9.0.x"

      - name: Build Linux
        working-directory: YetAnotherMinecraftLauncher
        run: |
          dotnet publish \
            -c Release \
            -r linux-x64 \
            --self-contained true \
            -o ../publish

      - name: Zip Linux build
        run: |
          cd publish
          zip -r ../YAMCL-linux.zip .

      - name: Upload Linux artifact
        uses: actions/upload-artifact@v4
        with:
          name: linux
          path: YAMCL-linux.zip

  build-win:
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v5
        with:
          dotnet-version: "9.0.x"

      - name: Build Windows
        working-directory: YetAnotherMinecraftLauncher
        run: |
          dotnet publish `
            -c Release `
            -r win-x64 `
            --self-contained true `
            -o ../publish

      - name: Zip Windows build
        run: Compress-Archive publish\* YAMCL-win.zip

      - name: Upload Windows artifact
        uses: actions/upload-artifact@v4
        with:
          name: windows
          path: YAMCL-win.zip

  release:
    needs: [build-linux, build-win]
    runs-on: ubuntu-latest
    steps:
      - name: Download artifacts
        uses: actions/download-artifact@v4

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          name: YAMCL ${{ github.ref_name }}
          files: |
            linux/YAMCL-linux.zip
            windows/YAMCL-win.zip
